apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: trade-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trade-service # Must match the name of the Deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80