apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-pvc
  labels:
    app: cryptobot
    tier: database
    service: auth
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi