apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  labels:
    app: cryptobot
    tier: database
    service: auth
spec:
  serviceName: auth-db
  replicas: 1
  selector:
    matchLabels:
      app: cryptobot
      tier: database
      service: auth
  template:
    metadata:
      labels:
        app: cryptobot
        tier: database
        service: auth
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: auth
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        volumeMounts:
        - name: auth-db-data
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - user
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - user
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: auth-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 10Gi