apiVersion: v1
kind: Service
metadata:
  name: auth-db
  labels:
    app: cryptobot
    tier: database
    service: auth
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: cryptobot
    tier: database
    service: auth