apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: cryptobot
    tier: backend
    service: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cryptobot
      tier: backend
      service: auth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cryptobot
        tier: backend
        service: auth
    spec:
      containers:
      - name: auth-service
        image: cryptobot/auth-service:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: auth-config
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5