apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cryptobot-prod
commonLabels:
  app: cryptobot
  environment: production
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- db-statefulset.yaml
- db-service.yaml
- db-pvc.yaml