apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: cryptobot
    tier: backend
    service: auth
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: cryptobot
    tier: backend
    service: auth