apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cryptobot-prod
commonLabels:
  app: cryptobot
  environment: production
resources:
- namespace.yaml
- auth-service/
- trade-service/
- strategy-service/
- backtest-service/
- data-service/