apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trade-service-monitor
  namespace: default
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: trade-service
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
      - default