apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategy-service
  labels:
    app: strategy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strategy-service
  template:
    metadata:
      labels:
        app: strategy-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8000'
    spec:
      containers:
      - name: strategy-service
        image: cryptobot/strategy-service:latest # Replace with your actual image name and tag
        ports:
        - containerPort: 8000
        # Add environment variables here if needed, e.g., for database connections
        # env:
        # - name: DATABASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secrets
        #       key: strategy_db_url
        livenessProbe:
          httpGet:
            path: /docs # Assuming /docs is available and indicates service health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /docs # Assuming /docs is available and indicates service readiness
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"