apiVersion: v1
kind: ConfigMap
metadata:
  name: trade-config
  labels:
    app: cryptobot
    tier: backend
    service: trade
data:
  # Exchange configuration
  EXCHANGE_SANDBOX: "false"
  
  # Rate limits for exchanges (requests per minute)
  BINANCE_RATE_LIMIT: "1200"
  COINBASE_RATE_LIMIT: "300"
  KRAKEN_RATE_LIMIT: "360"
  FTX_RATE_LIMIT: "30"
  
  # Service configuration
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
  
  # Database configuration (replace with actual values in production)
  DATABASE_URL: "postgresql://user:password@trade-db:5432/trade"