apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-service
  labels:
    app: cryptobot
    tier: backend
    service: trade
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cryptobot
      tier: backend
      service: trade
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cryptobot
        tier: backend
        service: trade
    spec:
      containers:
      - name: trade-service
        image: cryptobot/trade:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: trade-config
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/trades/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/trades/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5