apiVersion: v1
kind: Service
metadata:
  name: trade-service
  labels:
    app: cryptobot
    tier: backend
    service: trade
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: cryptobot
    tier: backend
    service: trade