apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        ports:
        - containerPort: 50051
          name: grpc
        - containerPort: 8001
          name: rest
        - containerPort: 8000
          name: metrics
        envFrom:
        - configMapRef:
            name: auth-config
        - secretRef:
            name: auth-secrets
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /auth/validate
            port: rest
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /auth/validate
            port: rest
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: rest
    port: 8001
    targetPort: 8001
  type: ClusterIP