groups:
- name: auth-service-alerts
  rules:
  - alert: HighFailedLoginRate
    expr: rate(failed_login_attempts_total[5m]) > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High failed login rate detected"
      description: "Failed login rate is {{ $value }} per second"

  - alert: TokenValidationErrors
    expr: rate(token_validation_errors_total[5m]) > 5
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High token validation error rate"
      description: "Token validation error rate is {{ $value }} per second"

  - alert: ServiceUnhealthy
    expr: service_health == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Auth service is unhealthy"
      description: "Service health check failed"