apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: default
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'alertmanager@example.com'
      smtp_auth_username: 'alertmanager'
      smtp_auth_password: 'password'
      smtp_require_tls: true
      slack_api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
      pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

    templates:
      - '/etc/alertmanager/template/*.tmpl'

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'slack-notifications'
      routes:
      - match:
          severity: critical
        receiver: 'pagerduty-critical'
        continue: true
      - match:
          severity: warning
        receiver: 'email-notifications'
        continue: true
      - match:
          team: trading
        receiver: 'trading-team-slack'
      - match:
          team: data
        receiver: 'data-team-slack'

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'cluster', 'service']

    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#alerts'
        send_resolved: true
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Cryptobot Monitoring Alert'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Service:* {{ .Labels.service }}
            *Time:* {{ .StartsAt }}
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* {{ .Value }}
            {{ end }}
          {{ end }}

    - name: 'email-notifications'
      email_configs:
      - to: 'team@example.com'
        send_resolved: true
        headers:
          subject: '[{{ .Status | toUpper }}] Cryptobot Alert: {{ .GroupLabels.alertname }}'
        html: |
          {{ range .Alerts }}
            <h3>{{ .Annotations.summary }}</h3>
            <p><strong>Description:</strong> {{ .Annotations.description }}</p>
            <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
            <p><strong>Service:</strong> {{ .Labels.service }}</p>
            <p><strong>Time:</strong> {{ .StartsAt }}</p>
            <h4>Details:</h4>
            <ul>
              {{ range .Labels.SortedPairs }}
                <li><strong>{{ .Name }}:</strong> {{ .Value }}</li>
              {{ end }}
            </ul>
          {{ end }}

    - name: 'pagerduty-critical'
      pagerduty_configs:
      - service_key: '0123456789abcdef0123456789abcdef'
        send_resolved: true
        description: '{{ .CommonAnnotations.summary }}'
        details:
          firing: '{{ .Alerts.Firing | len }}'
          status: '{{ .Status }}'
          instance: '{{ .CommonLabels.instance }}'
          service: '{{ .CommonLabels.service }}'

    - name: 'trading-team-slack'
      slack_configs:
      - channel: '#trading-alerts'
        send_resolved: true
        title: '[{{ .Status | toUpper }}] Trading Alert: {{ .GroupLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Service:* {{ .Labels.service }}
            *Time:* {{ .StartsAt }}
          {{ end }}

    - name: 'data-team-slack'
      slack_configs:
      - channel: '#data-alerts'
        send_resolved: true
        title: '[{{ .Status | toUpper }}] Data Alert: {{ .GroupLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Service:* {{ .Labels.service }}
            *Time:* {{ .StartsAt }}
          {{ end }}

    - name: 'webhook-receiver'
      webhook_configs:
      - url: 'http://custom-integration-service:8080/alert'
        send_resolved: true

  template.tmpl: |
    {{ define "slack.default.title" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}{{ end }}

    {{ define "slack.default.text" }}
    {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Details:*
      {{ range .Labels.SortedPairs }} • *{{ .Name }}:* {{ .Value }}
      {{ end }}
    {{ end }}
    {{ end }}