apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: default
  labels:
    app: alertmanager
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9093'
    prometheus.io/path: '/metrics'
spec:
  selector:
    app: alertmanager
  ports:
  - name: alertmanager
    port: 9093
    targetPort: 9093
    protocol: TCP
  type: ClusterIP