apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategy-service
  labels:
    app: cryptobot
    tier: backend
    service: strategy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cryptobot
      tier: backend
      service: strategy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cryptobot
        tier: backend
        service: strategy
    spec:
      containers:
      - name: strategy-service
        image: cryptobot/strategy:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: strategy-config
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5