name: Terraform Kafka Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/kafka/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/kafka/**'

env:
  AWS_REGION: "us-west-2"
  TF_VERSION: "1.5.0"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ./infra/kafka
        run: terraform init

      - name: Terraform Validate
        working-directory: ./infra/kafka
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./infra/kafka
        run: terraform plan -input=false
        continue-on-error: true

      - name: Terraform Apply
        working-directory: ./infra/kafka
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false