apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  labels:
    app: data-service
spec:
  replicas: 1 # Can be scaled based on load
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8001'
    spec:
      containers:
      - name: data-service
        image: cryptobot/data-service:latest # Replace with your actual image name and tag
        ports:
        - containerPort: 8001
        # Add environment variables here if needed (e.g., database, external APIs)
        # env:
        # - name: DATABASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secrets
        #       key: data_db_url
        livenessProbe:
          httpGet:
            path: /docs # Assuming /docs is available and indicates service health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /docs # Assuming /docs is available and indicates service readiness
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"